from __future__ import annotations


_BASE_SHADOW = {
    "color": "#000000",
    "blur_radius": 6,
    "offset_x": 0,
    "offset_y": 4,
    "opacity": 0.72,
}


CAPTION_PRESET_REGISTRY: dict[str, dict[str, object]] = {
    "bold_center": {
        "preset_id": "bold_center",
        "font_asset_id": "anton_regular_v1",
        "font_family": "Anton",
        "font_weight": 700,
        "font_case": "upper",
        "fill_color": "#FFF4D6",
        "inactive_fill_color": "#E7D8B0",
        "active_fill_color": "#FFD166",
        "stroke_color": "#111111",
        "stroke_width": 4.0,
        "shadow": _BASE_SHADOW,
        "highlight_mode": "phrase_pop",
        "default_zone": "lower_safe",
        "max_words_per_segment": 8,
        "line_break_policy": "balanced",
        "speaker_label_mode": "none",
        "font_size_px_1080x1920": 96,
        "line_height": 1.08,
        "letter_spacing": 0.5,
        "max_lines": 2,
        "safe_margin_bottom_px": 260,
        "active_scale": 1.08,
        "active_pop_in_ms": 90,
        "active_pop_out_ms": 120,
    },
    "karaoke_focus": {
        "preset_id": "karaoke_focus",
        "font_asset_id": "montserrat_extra_bold_v1",
        "font_family": "Montserrat",
        "font_weight": 800,
        "font_case": "as_is",
        "fill_color": "#FFFFFF",
        "inactive_fill_color": "#D9D9D9",
        "active_fill_color": "#FFE45E",
        "stroke_color": "#000000",
        "stroke_width": 4.0,
        "shadow": _BASE_SHADOW,
        "highlight_mode": "word_highlight",
        "default_zone": "lower_safe",
        "max_words_per_segment": 8,
        "line_break_policy": "punctuation_first",
        "speaker_label_mode": "none",
        "font_size_px_1080x1920": 92,
        "line_height": 1.1,
        "letter_spacing": 0.2,
        "max_lines": 2,
        "safe_margin_bottom_px": 280,
        "active_scale": 1.12,
        "active_pop_in_ms": 80,
        "active_pop_out_ms": 110,
    },
    "clean_lower": {
        "preset_id": "clean_lower",
        "font_asset_id": "ibm_plex_sans_semibold_v1",
        "font_family": "IBM Plex Sans",
        "font_weight": 600,
        "font_case": "as_is",
        "fill_color": "#FFFFFF",
        "inactive_fill_color": "#E5E5E5",
        "active_fill_color": "#FFFFFF",
        "stroke_color": "#0F172A",
        "stroke_width": 3.0,
        "shadow": _BASE_SHADOW,
        "highlight_mode": "phrase_static",
        "default_zone": "lower_safe",
        "max_words_per_segment": 10,
        "line_break_policy": "balanced",
        "speaker_label_mode": "none",
        "font_size_px_1080x1920": 76,
        "line_height": 1.16,
        "letter_spacing": 0.0,
        "max_lines": 2,
        "safe_margin_bottom_px": 320,
        "active_scale": 1.0,
        "active_pop_in_ms": 0,
        "active_pop_out_ms": 0,
    },
    "split_speaker": {
        "preset_id": "split_speaker",
        "font_asset_id": "space_grotesk_bold_v1",
        "font_family": "Space Grotesk",
        "font_weight": 700,
        "font_case": "as_is",
        "fill_color": "#F8FAFC",
        "inactive_fill_color": "#CBD5E1",
        "active_fill_color": "#93C5FD",
        "stroke_color": "#020617",
        "stroke_width": 3.5,
        "shadow": _BASE_SHADOW,
        "highlight_mode": "phrase_pop",
        "default_zone": "split_band",
        "max_words_per_segment": 7,
        "line_break_policy": "balanced",
        "speaker_label_mode": "speaker_id",
        "font_size_px_1080x1920": 82,
        "line_height": 1.1,
        "letter_spacing": 0.3,
        "max_lines": 2,
        "safe_margin_bottom_px": 260,
        "active_scale": 1.06,
        "active_pop_in_ms": 70,
        "active_pop_out_ms": 100,
    },
}
